/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.controllerDetail;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author WIN10
 */
public class detailPesanan extends javax.swing.JFrame {
    private adminView aV = new adminView();
    private controllerDetail cD;
    private String level;
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }
    
    
    
    /**
     * Creates new form detailPesanan
     */
//    public detailPesanan(adminView aV) {
//        initComponents();
//        this.aV = aV;
//    }
    public detailPesanan() {
        initComponents();
//        JOptionPane.showConfirmDialog(null, this.getLevel());
//        if (this.getLevel().equalsIgnoreCase("admin")){
//            idDetail.setEditable(false);
//            usernameDetail.setEditable(false);
//            estimasiDetail.setEditable(false);
//            kategoriDetail.setEditable(false);
//            jenisSabunDetail.setEditable(false);
//            alamatDetail.setEditable(false);
//        }else if (this.getLevel().equalsIgnoreCase("user")){
//            statusDetail.setEditable(false);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        konfirmDetail = new javax.swing.JButton();
        backDetail = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        statusDetail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatDetail = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idDetail = new javax.swing.JTextField();
        usernameDetail = new javax.swing.JTextField();
        estimasiDetail = new javax.swing.JTextField();
        kategoriDetail = new javax.swing.JTextField();
        jenisSabunDetail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        konfirmDetail.setText("Konfirm");
        konfirmDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmDetailActionPerformed(evt);
            }
        });

        backDetail.setText("Back");
        backDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDetailActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        alamatDetail.setColumns(20);
        alamatDetail.setRows(5);
        jScrollPane1.setViewportView(alamatDetail);

        jLabel6.setText("Alamat");

        jLabel5.setText("Jenis Sabun");

        jLabel4.setText("Kategori");

        jLabel3.setText("Estimasi Berat");

        jLabel2.setText("Username");

        jLabel1.setText("ID");

        idDetail.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(statusDetail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backDetail)
                        .addGap(18, 18, 18)
                        .addComponent(konfirmDetail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idDetail)
                            .addComponent(usernameDetail)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimasiDetail)
                            .addComponent(kategoriDetail)
                            .addComponent(jenisSabunDetail))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estimasiDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kategoriDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jenisSabunDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backDetail)
                    .addComponent(konfirmDetail)
                    .addComponent(hapusButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDetailActionPerformed
        // TODO add your handling code here:
//        aV.tampilData();
//        aV.setUsername(this.getUsername());
//        aV.setVisible(true);
//        this.dispose();
        
        if(this.getLevel().equalsIgnoreCase("admin")){
            aV.tampilData();
            aV.setUsername(this.getUsername());
            aV.setLevel("admin");
            aV.setVisible(true);
            
        }else if(this.getLevel().equalsIgnoreCase("user")){
            userView uV = new userView();
            uV.setUsername(this.getUsername());
            uV.setLevel("user");
            uV.setVisible(true);            
        }
        this.dispose();
    }//GEN-LAST:event_backDetailActionPerformed

    private void konfirmDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmDetailActionPerformed
        // TODO add your handling code here:
//        cD = new controllerDetail(this);
//        cD.konfirmasi();
//        aV.tampilData();
//        aV.setUsername(this.getUsername());
//        aV.setVisible(true);
//        this.dispose();
        
        if(this.getLevel().equalsIgnoreCase("admin")){
            cD = new controllerDetail(this);
            cD.konfirmasi();
            aV.tampilData();
            aV.setUsername(this.getUsername());
            aV.setLevel("admin");
            aV.setVisible(true);
            
        }else if(this.getLevel().equalsIgnoreCase("user")){
            cD = new controllerDetail(this);
            cD.konfirmasi();
            userView uV = new userView();
            uV.setUsername(this.getUsername());
            uV.setLevel("user");
            uV.setVisible(true);            
        }
        this.dispose();
        
    }//GEN-LAST:event_konfirmDetailActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        if(this.getLevel().equalsIgnoreCase("admin")){
            cD = new controllerDetail(this);
            cD.hapus();
            aV.tampilData();
            aV.setUsername(this.getUsername());
            aV.setLevel("admin");
            aV.setVisible(true);
            
        }else if(this.getLevel().equalsIgnoreCase("user")){
            cD = new controllerDetail(this);
            cD.hapus();
            userView uV = new userView();
            uV.setUsername(this.getUsername());
            uV.setLevel("user");
            uV.setVisible(true);            
        }
        this.dispose();
    }//GEN-LAST:event_hapusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailPesanan().setVisible(true);
            }
        });
    }

    public JTextArea getAlamatDetail() {
        return alamatDetail;
    }

    public void setAlamatDetail(String alamatDetail) {
        this.alamatDetail.setText(alamatDetail);
    }

    public JTextField getEstimasiDetail() {
        return estimasiDetail;
    }

    public void setEstimasiDetail(String estimasiDetail) {
        this.estimasiDetail.setText(estimasiDetail);
    }

    public JTextField getIdDetail() {
        return idDetail;
    }

    public void setIdDetail(String idDetail) {
        this.idDetail.setText(idDetail);
    }

    public JTextField getJenisSabunDetail() {
        return jenisSabunDetail;
    }

    public void setJenisSabunDetail(String jenisSabunDetail) {
        this.jenisSabunDetail.setText(jenisSabunDetail);
    }

    public JTextField getKategoriDetail() {
        return kategoriDetail;
    }

    public void setKategoriDetail(String kategoriDetail) {
        this.kategoriDetail.setText(kategoriDetail);
    }

    public JButton getKonfirmDetail() {
        return konfirmDetail;
    }

    public void setKonfirmDetail(JButton konfirmDetail) {
        this.konfirmDetail = konfirmDetail;
    }

    public JTextField getStatusDetail() {
        return statusDetail;
    }

    public void setStatusDetail(String statusDetail) {
        this.statusDetail.setText(statusDetail);
    }

    public JTextField getUsernameDetail() {
        return usernameDetail;
    }

    public void setUsernameDetail(String usernameDetail) {
        this.usernameDetail.setText(usernameDetail);
    }
    
    public void editableKondition(){
        //JOptionPane.showConfirmDialog(null, "Level : "+this.getLevel());
        if (this.getLevel().equalsIgnoreCase("admin")){
            idDetail.setEditable(false);
            usernameDetail.setEditable(false);
            estimasiDetail.setEditable(false);
            kategoriDetail.setEditable(false);
            jenisSabunDetail.setEditable(false);
            alamatDetail.setEditable(false);
        }else if (this.getLevel().equalsIgnoreCase("user")){
            statusDetail.setEditable(false);
            kategoriDetail.setEditable(false);
            jenisSabunDetail.setEditable(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatDetail;
    private javax.swing.JButton backDetail;
    private javax.swing.JTextField estimasiDetail;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenisSabunDetail;
    private javax.swing.JTextField kategoriDetail;
    private javax.swing.JButton konfirmDetail;
    private javax.swing.JTextField statusDetail;
    private javax.swing.JTextField usernameDetail;
    // End of variables declaration//GEN-END:variables
}
