/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.controllerPesan;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author WIN10
 */
public class pesanView extends javax.swing.JFrame {
    private controllerPesan cP;
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    
    /**
     * Creates new form pesanView
     */
    public pesanView() {
        initComponents();
        cP = new controllerPesan(this);
        //JOptionPane.showConfirmDialog(this, this.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sabunCairPesanView = new javax.swing.JRadioButton();
        konfirmPesanButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlamatPesanView = new javax.swing.JTextArea();
        kategoriVeryExpertPesanView = new javax.swing.JRadioButton();
        kategoriExpertPesanView = new javax.swing.JRadioButton();
        beratPesanView = new javax.swing.JTextField();
        KategoriNormalPesanView = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SabunBubukPesanView = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesan kurir");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        sabunCairPesanView.setBackground(new java.awt.Color(0, 204, 255));
        sabunCairPesanView.setText("Cair");
        sabunCairPesanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabunCairPesanViewActionPerformed(evt);
            }
        });

        konfirmPesanButton.setText("Konfirm");
        konfirmPesanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmPesanButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        AlamatPesanView.setColumns(20);
        AlamatPesanView.setRows(5);
        jScrollPane1.setViewportView(AlamatPesanView);

        kategoriVeryExpertPesanView.setBackground(new java.awt.Color(0, 204, 255));
        kategoriVeryExpertPesanView.setText("Very Expert");
        kategoriVeryExpertPesanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriVeryExpertPesanViewActionPerformed(evt);
            }
        });

        kategoriExpertPesanView.setBackground(new java.awt.Color(0, 204, 255));
        kategoriExpertPesanView.setText("Expert");

        KategoriNormalPesanView.setBackground(new java.awt.Color(0, 204, 255));
        KategoriNormalPesanView.setText("Normal");

        jLabel3.setText("Jenis Sabun");

        jLabel1.setText("Estimasi berat (kg) ");

        jLabel4.setText("Kategori");

        jLabel2.setText("Alamat lengkap");

        SabunBubukPesanView.setBackground(new java.awt.Color(0, 204, 255));
        SabunBubukPesanView.setText("Bubuk");

        jLabel6.setText("Pesan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(konfirmPesanButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(KategoriNormalPesanView)
                                            .addComponent(sabunCairPesanView))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SabunBubukPesanView)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(kategoriExpertPesanView)
                                                .addGap(18, 18, 18)
                                                .addComponent(kategoriVeryExpertPesanView)))))
                                .addComponent(beratPesanView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(beratPesanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(KategoriNormalPesanView)
                        .addComponent(kategoriExpertPesanView)
                        .addComponent(kategoriVeryExpertPesanView)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sabunCairPesanView)
                        .addComponent(SabunBubukPesanView)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(konfirmPesanButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kategoriVeryExpertPesanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriVeryExpertPesanViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriVeryExpertPesanViewActionPerformed

    private void sabunCairPesanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabunCairPesanViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabunCairPesanViewActionPerformed

    private void konfirmPesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmPesanButtonActionPerformed
        // TODO add your handling code here:
        cP.konfirmmasi();
        userView uV = new userView();
        uV.setUsername(this.getUsername());
        uV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_konfirmPesanButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userView uV = new userView();
        uV.setVisible(true);
        uV.setUsername(this.getUsername());
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanView().setVisible(true);
            }
        });
    }
    

    public JTextArea getAlamatPesanView() {
        return AlamatPesanView;
    }

    public JRadioButton getKategoriNormalPesanView() {
        return KategoriNormalPesanView;
    }

    public JRadioButton getSabunBubukPesanView() {
        return SabunBubukPesanView;
    }

    public JTextField getBeratPesanView() {
        return beratPesanView;
    }

    public JRadioButton getKategoriExpertPesanView() {
        return kategoriExpertPesanView;
    }

    public JRadioButton getKategoriVeryExpertPesanView() {
        return kategoriVeryExpertPesanView;
    }

    public JButton getKonfirmPesanButton() {
        return konfirmPesanButton;
    }

    public JRadioButton getSabunCairPesanView() {
        return sabunCairPesanView;
    }

    public void setAlamatPesanView(JTextArea AlamatPesanView) {
        this.AlamatPesanView = AlamatPesanView;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlamatPesanView;
    private javax.swing.JRadioButton KategoriNormalPesanView;
    private javax.swing.JRadioButton SabunBubukPesanView;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField beratPesanView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton kategoriExpertPesanView;
    private javax.swing.JRadioButton kategoriVeryExpertPesanView;
    private javax.swing.JButton konfirmPesanButton;
    private javax.swing.JRadioButton sabunCairPesanView;
    // End of variables declaration//GEN-END:variables
}
